blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Perfect-Abstractions/Compose/discussions
    about: Please ask and answer questions here.
  - name: Discord Community
    url: https://discord.gg/DCBD2UKbxc
    about: Join our Discord for real-time discussions and support.
