name: Post Coverage Comment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  pull-requests: write
  issues: write

jobs:
  comment:
    name: Post Coverage Comment
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download and post coverage comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const { execSync } = require('child_process');
            
            // Download artifact
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            
            const coverageArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === 'coverage-data'
            );
            
            if (!coverageArtifact) {
              console.log('No coverage artifact found');
              return;
            }
            
            console.log('Found coverage artifact, downloading...');
            
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: coverageArtifact.id,
              archive_format: 'zip',
            });
            
            // Save and extract the artifact using execSync
            const artifactPath = path.join(process.env.GITHUB_WORKSPACE, 'coverage-data.zip');
            fs.writeFileSync(artifactPath, Buffer.from(download.data));
            
            console.log('Artifact downloaded, extracting...');
            
            // Unzip the artifact
            execSync(`unzip -o ${artifactPath} -d ${process.env.GITHUB_WORKSPACE}`);
            
            // Extract PR number
            const prDataPath = path.join(process.env.GITHUB_WORKSPACE, 'coverage-data.txt');
            const prData = fs.readFileSync(prDataPath, 'utf8');
            const prMatch = prData.match(/PR_NUMBER=(\d+)/);
            
            if (!prMatch) {
              console.log('Could not find PR number in coverage-data.txt');
              return;
            }
            
            const prNumber = parseInt(prMatch[1]);
            console.log(`Processing coverage for PR #${prNumber}`);
            
            // Read coverage report
            const reportPath = path.join(process.env.GITHUB_WORKSPACE, 'coverage-report.md');
            const body = fs.readFileSync(reportPath, 'utf8');
            
            // Check if a coverage comment already exists
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('## Coverage Report')
            );
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
              console.log('Coverage comment updated successfully!');
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
              console.log('Coverage comment posted successfully!');
            }
