name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests with coverage
        run: |
          forge coverage --report lcov

      - name: Install coverage tools
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Process coverage report
        run: |
          # Find the coverage file that Foundry generated
          if [ -f lcov.info ]; then
            echo "Found lcov.info, processing..."
            lcov --remove lcov.info '*/test/*' '*/script/*' '*/lib/*' --output-file coverage.info
          else
            echo "No lcov.info found, looking for other coverage files..."
            ls -la *.lcov || echo "No .lcov files found"
            exit 1
          fi
          
          lcov --list coverage.info

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const lcov = fs.readFileSync('coverage.info', 'utf8');
            const lines = lcov.split('\n');
            const summary = lines.find(line => line.startsWith('LF:'));
            const hit = lines.find(line => line.startsWith('LH:'));
            
            if (summary && hit) {
              const total = summary.split(':')[1];
              const covered = hit.split(':')[1];
              const percentage = Math.round((covered / total) * 100);
              
              const comment = `## Test Coverage Report
              
              **Coverage: ${percentage}%** (${covered}/${total} lines)
              
              <details>
              <summary>View detailed coverage report</summary>
              
              \`\`\`
              ${lcov}
              \`\`\`
              </details>`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
