name: Slither


on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        run: forge build

      - name: Install Slither
        run: |
          pip install slither-analyzer

      - name: Run Slither analysis
        run: |
          slither . --exclude-dependencies